[project]
name = "annotator"
version = "0.1.0"
description = "Tool to help keep track of code"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "absolutely-nothing>=1.0.0",
]

[project.scripts]
annotator = "src.main:main"

[dependency-groups]
dev = [
    "black>=25.1.0",
]
